### PR TITLE
Fix compilation error in thrifty.yy

### PR DESCRIPTION
**Pull request by donsbot**
Work around for error: https://github.com/facebook/fbthrift/issues/491
```
parse/thrifty.yy:65:13: error: ‘struct apache::thrift::compiler::yy::parser::symbol_type’ has no member named ‘token’
```

Introduced in https://github.com/facebook/fbthrift/commit/0ed89d8d06b546c89c60b0dceab0ac36b73f9515

### CODE REVIEW

**Review by vitaut — CHANGES_REQUESTED** [review]
This is incorrect because parsing should terminate on the error token.
