### ISSUE TITLE
fizz integration: no matching constructor for initialization of 'wangle::FizzAcceptorHandshakeHelper'

### ISSUE THREAD

**Issue by donsbot** [facebook/fbthrift#556]
Broken integration wrt. fizz. 

```
[2/63] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/security/FizzPeeker.cpp.o
FAILED: thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/security/FizzPeeker.cpp.o
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DGFLAGS_IS_A_DLL=0 -DTHRIFT_HAVE_LIBSNAPPY=0 -Dthriftcpp2_EXPORTS -I/tmp/fbcode_builder_getdeps-ZhomeZdonsZGleanZhsthriftZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/. -I. -isystem /usr/include/libiberty -isystem /home/dons/.hsthrift/include -fsized-deallocation -O2 -g -DNDEBUG -fPIC -fsized-deallocation -std=c++17 -MD -MT thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/security/FizzPeeker.cpp.o -MF thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/security/FizzPeeker.cpp.o.d -o thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/security/FizzPeeker.cpp.o -c /tmp/fbcode_builder_getdeps-ZhomeZdonsZGleanZhsthriftZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp2/security/FizzPeeker.cpp
/tmp/fbcode_builder_getdeps-ZhomeZdonsZGleanZhsthriftZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp2/security/FizzPeeker.cpp:73:9: error: no matching constructor for initialization of 'wangle::FizzAcceptorHandshakeHelper'
      : wangle::FizzAcceptorHandshakeHelper::FizzAcceptorHandshakeHelper(
        ^
/home/dons/.hsthrift/include/wangle/acceptor/FizzAcceptorHandshakeHelper.h:221:3: note: candidate constructor not viable: requires 7 arguments, but 6 were provided
  FizzAcceptorHandshakeHelper(
  ^
/home/dons/.hsthrift/include/wangle/acceptor/FizzAcceptorHandshakeHelper.h:215:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
class FizzAcceptorHandshakeHelper
      ^
/tmp/fbcode_builder_getdeps-ZhomeZdonsZGleanZhsthriftZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp2/security/FizzPeeker.cpp:86:5: error: use of undeclared identifier 'sslContext_'
    sslContext_ = sock->getSSLContext();
    ^
2 errors generated.
```

**Comment by donsbot** [comment]
Broken in https://github.com/facebook/fbthrift/commit/2a059bda27b7865f5f735002867900f6187e5be9
