### ISSUE TITLE
Linker error: libthriftcpp2.so: error: undefined reference to 'apache::thrift::TrustedServerException::unimplementedMethodError(char const*)'

### ISSUE THREAD

**Issue by donsbot** [facebook/fbthrift#476]
A recent change is causing linker errors when trying to link against libthriftcpp2.so (found when building hsthrift against fbthrift main both from source).

Two symbols are not found:
```
libthriftcpp2.so: error: undefined reference to 'apache::thrift::TrustedServerException::requestParsingError(char const*)'
```

and
```
libthriftcpp2.so: error: undefined reference to 'apache::thrift::TrustedServerException::unimplementedMethodError(char const*)
```

I can avoid this by building from commit b80cfa67c7afcdaf1c4254f604f1d3e8a6636a8c before the recent changes that added this new exception type.

Suspect something in 51a28d520f58b5e28c26078b70f57d856a16bdb6 69a50413c04db89413d39d54e94b852dba5bd65e etc.

**Comment by vitaut** [comment]
This is caused by https://github.com/facebook/fbthrift/commit/51a28d520f58b5e28c26078b70f57d856a16bdb6 and we are working on a fix. Thanks for reporting.

**Comment by simonmar** [comment]
Fixed by abd5ad5983245099d996bba01312b97992bd6092
