### ISSUE TITLE
libthrift does not properly link against boost

### ISSUE THREAD

**Issue by matthiasplappert** [facebook/fbthrift#100]
The problem is that thrift uses threading capabilities from boost. However, it does not seem to link properly against the necessary boost libraries. This problem becomes apparent when attempting to install https://github.com/facebook/thpp:

```
root@eedd7f423290:/tmp/thpp/thpp/build# cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Folly: /usr/local/include
-- Found Glog: /usr/include
-- Found Torch7 in /usr/local
-- Found Thrift: /usr/local/include
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/thpp/thpp/build
root@eedd7f423290:/tmp/thpp/thpp/build# make
[  7%] Generating thpp/if/gen-cpp2/Tensor_types.h, thpp/if/gen-cpp2/Tensor_types.tcc, thpp/if/gen-cpp2/Tensor_constants.h, thpp/if/gen-cpp2/Tensor_types.cpp, thpp/if/gen-cpp2/Tensor_constants.cpp
Scanning dependencies of target thpp
[ 15%] Building CXX object CMakeFiles/thpp.dir/Storage.cpp.o
[ 23%] Building CXX object CMakeFiles/thpp.dir/StorageSerialization.cpp.o
[ 30%] Building CXX object CMakeFiles/thpp.dir/detail/StorageDefs.cpp.o
[ 38%] Building CXX object CMakeFiles/thpp.dir/TensorSerialization.cpp.o
[ 46%] Building CXX object CMakeFiles/thpp.dir/detail/TensorDefs.cpp.o
[ 53%] Building CXX object CMakeFiles/thpp.dir/thpp/if/gen-cpp2/Tensor_types.cpp.o
[ 61%] Building CXX object CMakeFiles/thpp.dir/thpp/if/gen-cpp2/Tensor_constants.cpp.o
/tmp/thpp/thpp/build/thpp/if/gen-cpp2/Tensor_constants.cpp:11:257: warning: 'TensorConstants' is deprecated (declared at /tmp/thpp/thpp/build/thpp/if/gen-cpp2/Tensor_constants.h:17): TensorConstants suffers from the 'static initialization order fiasco' (https://isocpp.org/wiki/faq/ctors#static-init-order) and may CRASH you program. Instead, use Tensor_constants::CONSTANT_NAME [-Wdeprecated-declarations]
 const TensorConstants __attribute__((__deprecated__("g_Tensor_constants suffers from the 'static initialization order fiasco' (https://isocpp.org/wiki/faq/ctors#static-init-order) and may CRASH you program. Instead, use Tensor_constants::CONSTANT_NAME"))) g_Tensor_constants;
                                                                                                                                                                                                                                                                 ^
Linking CXX shared library libthpp.so
[ 61%] Built target thpp
Scanning dependencies of target gtest
[ 69%] Building CXX object gtest-1.7.0/CMakeFiles/gtest.dir/src/gtest-all.cc.o
Linking CXX static library libgtest.a
[ 69%] Built target gtest
Scanning dependencies of target gtest_main
[ 76%] Building CXX object gtest-1.7.0/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
Linking CXX static library libgtest_main.a
[ 76%] Built target gtest_main
Scanning dependencies of target storage_test
[ 84%] Building CXX object test/CMakeFiles/storage_test.dir/StorageTest.cpp.o
Linking CXX executable storage_test
[ 84%] Built target storage_test
Scanning dependencies of target tensor_serialization_test
[ 92%] Building CXX object test/CMakeFiles/tensor_serialization_test.dir/TensorSerializationTest.cpp.o
Linking CXX executable tensor_serialization_test
/usr/local/lib/libthrift.so: undefined reference to `boost::this_thread::interruption_point()'
/usr/local/lib/libthriftcpp2.so: undefined reference to `boost::this_thread::disable_interruption::disable_interruption()'
/usr/local/lib/libthriftcpp2.so: undefined reference to `boost::this_thread::disable_interruption::~disable_interruption()'
/usr/local/lib/libthrift.so: undefined reference to `boost::detail::get_current_thread_data()'
collect2: error: ld returned 1 exit status
make[2]: *** [test/tensor_serialization_test] Error 1
make[1]: *** [test/CMakeFiles/tensor_serialization_test.dir/all] Error 2
make: *** [all] Error 2
```

I attempt to build on Ubuntu 14.04 with all requirements installed. If I disable the tests I can install thpp, but it will not work during runtime for the same linking problems as above.

**Comment by arjenroodselaar** [comment]
I accidentally broke this last week. A fix is in review and should land shortly.

**Comment by sneiman** [comment]
Appears this is still broken as of today. Can you share a likely fix date?

thanks,

s

**Comment by ryluo** [comment]
Any work around?

Thanks,
R

**Comment by sneiman** [comment]
cant be certain but I am following this thread right now:
https://github.com/facebook/fbcunn/issues/51

promising - but not done yet.

**Comment by arjenroodselaar** [comment]
The fix for this got stuck while waiting for Jenkins to give green light on my patch. I kicked it off again and it will land. In the meantime, feel free to apply the following against your fbthrift checkout: https://gist.github.com/arjenroodselaar/bc189172bb67dd5f1429.

**Comment by sneiman** [comment]
Worked like a charm – thanks.

Seth

This entire message is confidential. If it isn't intended for you, you may not use it – so please throw it away and forget about it.

**Comment by sneiman** [comment]
Do you mind if I post a reference to hear on the torch site?

**Comment by arjenroodselaar** [comment]
Nope, go for it. The above diff just landed in our internal repo and I will make sure a new fbthrift will happen soon. Apologies again for breaking this.

**Comment by sneiman** [comment]
It happens ;) I appreciate the direct contact to keep me moving forward.

S

This entire message is confidential. If it isn't intended for you, you may not use it – so please throw it away and forget about it.

**Comment by arjenroodselaar** [comment]
This has been fixed in v28.
